### ISSUE TITLE
Question:  why the error bar in spectra_cn.png is higher than that in asm.st.png

### ISSUE THREAD

**Issue by cchd0001** [marbl/merqury#10]
Hi , 

I noticed that the error bar in spectra_cn.png is higher than than in asm.st.png. Howerver , if both of them refer to  the assembly k-mers absent from the read set, they should be consistent.

To figure out their difference, I had read related souce codes but only found I was even more confused.

Here is my understanding of related source codes: 

1. In asm.st.png , the total height of error bar refers to "the total number of assembly **k-mer types**  absent from the read set".
       1. 1  In meryl statistics this value is named by "distinct".
2. In spectra_cn.png, the total height of error bar  refers to the total number of assembly **k-mers**  absent from the read set , where **k-mers**=accumulation( each k-mer type's multiplicity). 
      2.1  In meryl statistics this value is named by "persent".
      2.2 The  height of error bar colored by copy-number-one color refer to "distinct".
      2.2  The  height of error bar colored by copy-number-two color refer to  "persent"-"distinct" .
           2.2.1 Thoes kmers in  "persent"-"distinct"  may have a copy number larger than 2.

I'm not sure whether this is a specific design or a bug. 

Best wishes
Lidong Guo

**Comment by arangrhie** [comment]
Hi Lidong,

Good catch.

In spectra-cn, the error bar is currently designed to plot k-mers found in the assembly once and multiple times.
"Present" contains all distinct k-mers x counts (frquency) in the assembly, which may be larger than 2.
I remember once plotted by copy number, the bar did not became visible and not so informative do distinguish copy number >3 very well.
To get the exact copy number histogram, try this:
```shell
meryl difference asm.meryl read.meryl output asm.0.meryl
meryl histogram asm.0.meryl > asm.0.hist
```
`asm.0.hist` contains the copy number in the first, frequency in the last column.
I will add this later as an option for plotting exact copy-numbers in error bar.
To clarify, the total height will not change. Only the coloring will reflect the copy number spectrum.

In spectra-asm, the purpose is to compare the k-mers regardless of copy-numbers.
It essentially tries to answers the question:
"How many distinct k-mers do I see only in my assembly 1and only in assembly 2? How much are shared?"
Coloring copy numbers of each category was having too much information in one bar.
So, the bar in spectra-asm becomes smaller when comparing to the spectra-cn because of this copy number ignorance.

I see plotting the presenting k-mers in asm1 only, asm2 only, shared may be informative and less confusing.
Will add this as well as an option in plotting if you think this will become useful.

For your interest, the way to extract exact copy-numbers in spectra-asm error bar is as following:

```shell
# Remove k-mers found in read.meryl
meryl difference asm1.meryl read.meryl output asm1.0.meryl    # asm1 only, not in reads
meryl difference asm2.meryl read.meryl output asm2.0.meryl    # asm2 only, not in reads

# asm1-only
meryl difference asm1.0.meryl asm2.0.meryl output asm1.0_not_asm2.0.meryl   # asm1-only in the error bar
meryl histogram asm1.0_not_asm2.0.meryl  > asm1.0_not_asm2.0.hist           # Histogram containing exact k-mer counts for asm1-only

# asm2-only
meryl difference asm2.0.meryl asm1.0.meryl output asm2.0_not_asm2.0.meryl   # for asm2-only
meryl histogram asm2.0_not_asm2.0.meryl > asm2.0_not_asm2.0.hist            # Histogram of asm2-only

# Shared, counts in asm1-only
meryl intersect asm1.0.meryl asm2.0.meryl output asm1.0_and_asm2.0.meryl     # Get shared, preserve counts in asm1
meryl histogram asm1.0_and_asm2.0.meryl > asm1.0_and_asm2.0.hist             # histogram of shared, copy numbers in asm1

# Shared, counts in asm2-only
meryl intersect asm2.0.meryl asm1.0.meryl output asm2.0_and_asm1.0.meryl      # Get shared, preserve counts in asm2
meryl histogram asm2.0_and_asm1.0.meryl > asm2.0_and_asm1.0.hist              # histogram of shared, copy numbers in asm2
```

**Comment by cchd0001** [comment]
Great . Thank you for the detailed answer.
