### ISSUE TITLE
Uneven maternal and paternal illumina reads set?

### ISSUE THREAD

**Issue by yjiang296** [marbl/merqury#141]
Hi! 
I wonder whether the uneven size of maternal and paternal illumina reads (like 300 million VS. 400 million reads) used to build parents' meryl dbs would affect phasing results? If so, should I randomly selected the same amount of maternal and paternal illumina reads to make them compare? 
Thanks in advance.

**Comment by arangrhie** [comment]
Hi @yjiang296 ,

If you have Illumina reads for the child, use [hapmers.sh](https://github.com/marbl/merqury/blob/master/trio/hapmers.sh). This script automatically does the intersection with the child kmers, and at the end you get kmers that are 'parental specific, inherited' to the child (hapmers).

This often helps avoiding issues caused by different sequencing coverage in the parents.

Best,
Arang

**Comment by yjiang296** [comment]
For child, I used HiFi reads, I hope its OK.
'sh $MERQURY/trio/hapmers.sh maternal.meryl paternal.meryl child.meryl' 
You mean this step can solve issues caused by different sequencing coverage in the parents ?
Thank you for your quick reply.
