### ISSUE TITLE
Discrepancy between Genomescope vs Merqury in predicted genome size

### ISSUE THREAD

**Issue by kneubehl** [marbl/merqury#16]
Hi there,

I am working on some Borrelia genomes (lots of linear plasmids [10kb to 200kb] some circular plasmids [30kb-90kb] and a linear chromosome [~900kb]) which contain a high amount of repetitive content. I used Merqury (which is really cool and may prove super useful) and got encouraging results in terms of accuracy and completeness and confirmed my suspicions about some areas that I thought didn't assemble properly. I wanted to quantify the repetitive genome content/confirm predicted genome size and looked to use the read.hist file on Genomescope. The predicted genome size on Genomescope is much larger than what the completeness reflects in the Merqury output (e.g. my assembly is ~1.5Mb and Merqury indicates this is 98% complete but on Genomescope, k=15, ploidy 1, the predicted size is ~2Mb). Am I conceptually missing something here in how Merqury and Genomescope calculate the predicted genome size?

**Comment by arangrhie** [comment]
Hello @kneubehl ,

Glad you find this cool :)

In Merqury, completeness is using distinct kmers, kmers distinctly found in the reads, regardless of its copy number. It does a hard-cutoff of the low-frequency kmer sets beforehand and looks how many of these distinct kmers are found in the assembly.

Genome size estimation is slightly different from this concept, and GenomeScope is more accurate in the sense that it models the repeats.

So, the difference you see from GenomeScope's genome size and the num. of distinct kmers are mostly comprised of the repetitive kmers. It wasn't easy to estimate completeness of the repetitive kmers and its copy numbers correctly, especially in the higher copy numbers due to sampling biases and other sequencing artifacts.

I think you could simply say "k-mer completeness measured with Mequry was 98%".

Thanks,
Arang

**Comment by kneubehl** [comment]
Thanks for the help!
