### ISSUE TITLE
The words on the picture are garbled

### ISSUE THREAD

**Issue by YiRan0220** [marbl/merqury#41]
Hi,
I have a problem with this output picture. Why is the text above scrambled? I have tried to reanalyze it for many times, but the result is the same.

sincerely,
YiRan
![test athal_CVI cvi0 hapmer spectra-cn st](https://user-images.githubusercontent.com/81667212/113089938-3d96d700-921b-11eb-8dc0-bafdecaf6fb1.png)
![test athal_CVI cvi0 hapmer spectra-cn fl](https://user-images.githubusercontent.com/81667212/113089942-3f609a80-921b-11eb-8ae2-b93308afcda9.png)
![test athal_CVI cvi0 hapmer spectra-cn ln](https://user-images.githubusercontent.com/81667212/113089944-3ff93100-921b-11eb-8ff0-be0ede9b0ac2.png)

**Comment by brianwalenz** [comment]
I've seen this - in other apps - when I don't have the correct font installed, but usually only for the 'fancy' symbols like emoji.  Since this is just standard normal letters (the label on the X axis in the bottom picture reads `6B=k` `6D=m` `65=e` `72=r` `5f=_` and so on) and I'd have to suspect something is wrong with your R installation.

Here's a couple of links to others with a similar problem, but no solution that I saw:
https://stackoverflow.com/questions/59796585/r-plots-corrupted-missing-characters-for-devices-other-than-pdf
https://stackoverflow.com/questions/60565754/greek-letters-in-r-expressions-result-in-missing-glyph

**Comment by YiRan0220** [comment]
Thanks! Yes, it is my R installation problem. It may be because the R version is too low. I updated R from 3.6.1 to 4.0.3 and solved the problem perfectly. Thank you very much!

**Comment by YiRan0220** [comment]
Hello，
 Another question, can I output images to PDF files, I have not found the relevant command options, thank you

**Comment by arangrhie** [comment]
Seems like for some OS, the R isn't installed to use the cairo engine by default.
I added this to commit ff0f689e72cf76b42972a3e6095acefec07810c2 to explicitly set the plotting engine as cairo.

```Rscript $MERQURY/plot/plot_spectra_cn.R --help```
Will give you other options. Use `-p` to output in pdf.

Thanks,
Arang
