### ISSUE TITLE
Merqury or Merfin?

### ISSUE THREAD

**Issue by JohnUrban** [marbl/merqury#75]
Hi all,

I am gearing up to do some assembly evaluations, and looking at the various available tools to do so.

It appears that Merfin in someways is meant to replace Merqury. Is that correct?

Posed another way, in what scenarios would I use Merqury, and which would I use Merfin?

Many thanks for any help.

Best,

John Urban

**Comment by JohnUrban** [comment]
As a follow-up -- are illumina reads required for using Merqury (and Merfin), or can one use nanopore reads (that are >90% accurate)?

**Comment by skoren** [comment]
No to using ONT reads, the k-mer histograms are too noisy still. You can use HiFi reads in most cases.

Merfin has a different QV estimate that's more sensitive to collapses/expansions in the assembly. If a genome has an identical two copy repeat but the assembly only represents it once, Merqury would give it a perfect QV score since all k-mers (except the few at the junction of the second copy) are present and none are erroneous. Merfin would give a lower score because it compares copy counts of k-mers as well. So you could use merfin instead of merqury for QV. Merfin can also filter your polishing change candidates which merqury cannot do.

All the trio coloring functionality, phase evaluation, blob plots, etc are only available in merqury.

**Comment by JohnUrban** [comment]
Thanks @skoren. Sounds good - I will have Illumina data soon enough. Thanks for the breakdown on Merqury and Merfin!

I will close up.
